### ISSUE TITLE
psm panic on run

### ISSUE THREAD

**Issue by johnsonjh** [bpowers/psm#2]
psm doesn't execute on my system when built using `go version devel +72a9dec Sun Sep 27 06:23:18 2020 +0000 linux/amd64`, nor when attempting installation via `go get -t -u github.com/bpowers/psm`, nor `go get github.com/bpowers/psm`, as well as failing when built from from a fresh checkout from of your git master branch - all of which return the same output.

The host system is Fedora 33 (Branched) on kernel 5.8.11, but I am do not normally, by default, use the Fedora/Red Hat distributed version of Golang toolchain, except to boostrap the build of Google's toolchain sources (master branch) from a Git checkout. The resulting compilation is then used to recompile the master branch toolchain again, and this toolchain is my the used as the primary Golang compiler on my system. [Edit: I use the Golang `toolstash` utility (`pkg.go.dev/golang.org/x/tools/cmd/toolstash`) as a standard part of my Golang setup and to ensure that my compilers are functioning properly.]

In this case, in my attempts to build and run `psm`, and to eliminate the possibility of any issue with the latest Git compiler, I attempted using the Google-distributed Golang binary toolchain (`go version go1.15.2 linux/amd64`) as well, but with exactly the same results.

The following output below is what was produced, verbatim, with `psm` compiled was compiled by Google's Git compiler from the the previously mentioned Git checkout. 

My only local modification to your work was building with the `-trimpath` option, to avoid exposing my local paths when making this report.

```
$ sudo ./psm

panic: NewMapInfo(1): `THPeligible:		0`

goroutine 11 [running]:
main.NewMapInfo(0xc000118289, 0xf, 0xd77, 0xd00, 0x0, 0x0)
	psm/main.go:59 +0x3a5
main.procMem(0x3f8, 0xc0001020f0, 0xc, 0x0, 0x0, 0x0, 0x0)
	psm/proc_linux.go:122 +0x34e
main.worker(0xc0000d6000, 0xc0000d2200, 0xc00002e2a0)
	psm/main.go:97 +0x185
created by main.main
	psm/main.go:168 +0x39e
panic: NewMapInfo(1): `THPeligible:		0`

goroutine 17 [running]:
main.NewMapInfo(0xc0000d5291, 0xf, 0xd6f, 0xd00, 0x0, 0x0)
	psm/main.go:59 +0x3a5
main.procMem(0x1, 0xc000016599, 0x7, 0x0, 0x0, 0x0, 0x0)
	psm/proc_linux.go:122 +0x34e
main.worker(0xc0000d6000, 0xc0000d2200, 0xc00002e2a0)
	psm/main.go:97 +0x185
created by main.main
	psm/main.go:168 +0x39e
```

I also built `psm` using the Fedora/Red Hat provided gccgo (`go version go1.14.6 gccgo (GCC) 10.2.1 20200826 (Red Hat 10.2.1-3) linux/amd64`), which produced the following, nearly identical, output:

```
panic: NewMapInfo(1): `THPeligible:		0`

goroutine 31 [running]:
main.NewMapInfo
	./main.go:64
main.procMem
	./proc_linux.go:122
main.worker
	./main.go:97
created by main.main
	./main.go:168 +0x5d7
panic: NewMapInfo(1): `THPeligible:		0`

goroutine 25 [running]:
main.NewMapInfo
	./main.go:64
main.procMem
	./proc_linux.go:122
main.worker
	./main.go:97
created by main.main
	./main.go:168 +0x5d7
```

I have not attempted any investigation (not even the most cursory or basic debugging effort at this point), but felt you would be interested to know of my experience, regardless. 

I am willing to help beyond simply reporting the issue, however; at this exact and particular moment, my schedule just doesn't allow for it, and for that I apologise. Being familiar with both `ps_mem.py`, and `smem`, I think `psm` would be something I would like in my toolkit.

Edit: Noticing that a Ubuntu PPA is provided, I downloaded `http://ppa.launchpad.net/bobbypowers/psm/ubuntu/pool/main/p/psm/psm_0.5.6-1_amd64.deb` which I then extracted using GNU atool (`atool -x psm_0.5.6-1_amd64.deb`), and executed it's extracted output using `sudo ./psm_0.5.6-1_amd64/usr/bin/psm`, which was, surprisingly, successful.  

A redacted dump of this output appears below:

```
    MB RAM    SHARED   SWAPPED	PROCESS (COUNT)
       0.2       0.0          	uptimed (1)
       0.2       0.0          	fusermount (1)
       0.3       0.0          	lsmd (1)
       0.3       0.1          	tee (2)
       0.3       0.2       0.5	zsh (2)
       0.4       0.0          	earlyoom (1)
       0.4       0.1          	server (1)
       0.4       0.0          	irqbalance (1)
       0.4       0.0          	incrond (1)
       0.4       0.3          	avahi-daemon: chroot helper (1)
       0.4       0.1          	rtkit-daemon (1)
       0.5       0.0          	less (1)
       0.5       0.1          	gnome-session-ctl (1)
       0.5       0.1          	alsactl (1)
       0.6       0.2       0.2	crashpad_handler (1)
       0.7       0.1          	gdm-wayland-session (1)
       0.8       0.1          	xdg-permission-store (1)
       0.8       0.1          	xinetd (1)
       0.9       0.1          	gsd-screensaver-proxy (1)
       0.9       0.2          	ssh-agent (1)
       0.9       0.1          	/sbin/auditd (1)
       1.0       0.1          	gsd-a11y-settings (1)
       1.0       0.1          	crond (1)
       1.0       0.1          	at-spi2-registryd (1)
       1.0       0.1          	gvfs-mtp-volume-monitor (1)
       1.0       0.2          	ibus-dconf (1)
       1.0       0.1          	flatpak-session-helper (1)
       1.0       0.1          	gsd-rfkill (1)
       1.0       0.2          	gssproxy (1)
       1.1       0.1          	gvfs-goa-volume-monitor (1)
       1.1       0.1          	gsd-usb-protection (1)
       1.1       0.1          	at-spi-bus-launcher (1)
       1.1       0.4       0.0	gpg-agent (2)
       1.1       0.3          	avahi-daemon: running [REDACTED] (1)
       1.1       0.7          	/app/main/chrome-sandbox (1)
       1.2       0.1          	gvfsd-fuse (1)
       1.2       0.1          	chronyd (1)
       1.2       0.1          	gconfd-2 (1)
       1.2       0.1          	gvfsd-metadata (1)
       1.2       0.1          	boltd (1)
       1.3       0.3          	obexd (1)
       1.3       0.1          	xdg-document-portal (1)
       1.3       0.2          	gvfsd (1)
       1.3       0.5          	bwrap (5)
       1.3       0.6          	dnsmasq (2)
       1.4       0.2          	gvfs-gphoto2-volume-monitor (1)
       1.4       0.3          	dbus (1)
       1.5       0.2          	-ircd resolver daemon (1)
       1.5       0.2          	gvfsd-dnssd (1)
       1.5       0.2          	ibus-engine-simple (1)
       1.6       0.2          	gsd-housekeeping (1)
       1.6       0.4          	nm-dispatcher (1)
       1.6       0.2       0.1	gdm (1)
       1.6       0.2          	/sbin/rngd (1)
       1.6       0.3          	fprintd (1)
       1.7       0.2          	sshd: /usr/sbin/sshd -D [listene (1)
       1.7       0.5          	systemd-machined (1)
       1.7       0.2          	ibus-portal (1)
       1.8       0.2          	gvfsd-network (1)e
       1.8       0.4          	gsd-sound (1)
       1.8       0.1          	-ircd bandb daemon (1)
       1.8       0.3          	gsd-disk-utility-notify (1)
       1.8       0.3          	gvfsd-http (1)
       1.9       0.2          	gvfsd-trash (1)
       1.9       0.1          	smartd (1)
       2.0       0.2          	upowerd (1)
       2.0       0.6          	goa-identity-service (1)
       2.2       0.5       0.1	dbus-broker-launch (3)
       2.2       0.4          	gsd-print-notifications (1)
       2.3       0.1          	dconf-service (1)
       2.5       0.1          	-ircd ssld daemon helper (1)
       2.5       0.4          	gsd-sharing (1)
       2.7       0.5          	gsd-printer (1)
       2.9       0.3          	gnome-keyring-daemon (1)
       2.9       0.6          	gsd-smartcard (1)
       2.9       0.4          	gvfs-udisks2-volume-monitor (1)
       3.0       0.4       0.1	cupsd (1)
       3.0       0.6          	systemd-logind (1)
       3.1       0.8          	pipewire-media-session (1)
       3.1       0.9       0.8	tmux (2)
       3.1       0.0       0.1	haveged (1)
       3.2       2.0          	keepassxc-proxy (1)
       3.6       0.9       0.0	abrt-dbus (1)
       3.8       0.3          	wpa_supplicant (1)
       4.0       0.0          	./psm_0.5.6-1_amd64/usr/bin/psm (1)
       4.1       0.7       0.0	cjdroute-crashey (2)
       4.1       0.5          	xdg-dbus-proxy (5)
       4.1       0.8          	pipewire (1)
       4.4       1.0          	abrt-applet (1)
       4.5       0.4       0.3	ircd (1)
       4.6       0.7          	sudo (2)
       5.2       0.6          	xdg-desktop-portal (1)
       5.6       0.6       0.0	udisksd (1)
       5.6       0.8          	ibus-x11 (1)
       5.8       1.1          	gnome-session-binary (2)
       6.1       0.1          	p11-kit-remote (1)
       6.2       0.6       0.6	gsd-keyboard (1)
       6.2       0.6       0.1	/usr/lib/systemd/systemd-udevd (1)
       6.2       0.5       0.1	colord (1)
       6.3       0.6       0.6	gsd-wacom (1)
       6.7       0.7       0.6	gsd-power (1)
       6.8       1.7          	gnome-shell-calendar-server (1)
       7.0       0.1       0.3	accounts-daemon (1)
       7.0       1.3          	pulseaudio (1)
       7.5       1.0       0.6	gsd-color (1)
       7.9       0.8       0.0	NetworkManager (1)
       8.0       0.5          	gdm-session-worker [pam/gdm-pass (1)
       8.0       0.2          	ibus-daemon (1)
       8.4       1.3       0.6	gsd-media-keys (1)
       8.5       2.8          	(sd-pam) (3)
       8.8       0.1          	nvim (1)
       9.3       0.3          	dbus-broker (3)
       9.6       4.1          	gjs-console (1)
      10.2       0.8          	geoclue (1)
      10.4       0.6       0.6	ibus-extension-gtk3 (1)
      12.6       3.4       0.3	polkitd (1)
      13.3       4.9          	WebKitNetworkProcess (1)
      14.7       0.7       0.6	xdg-desktop-portal-gtk (1)
      15.5       1.2       0.6	seahorse (1)
      15.7       3.8          	systemd (4)
      16.8       1.1          	gsd-datetime (1)
      17.4       3.0          	gsd-xsettings (1)
      17.4       2.9          	perl (4)
      18.3       1.7          	systemd-journald (1)
      19.6       2.0          	evolution-source-registry (1)
      21.0       0.1       0.2	yggdrasil (1)
      23.9       6.7       0.4	evolution-alarm-notify (1)
      26.0       1.9          	mosh-client (3)
      27.4       3.4          	evolution-calendar-factory (1)
      32.1       1.4       0.0	rsyslogd (1)
      32.7       3.5          	goa-daemon (1)
      34.9       0.4       1.7	unbound (1)
      40.3       0.1       0.2	snapd (1)
      41.2       4.3       0.0	Xwayland (1)
      45.1       0.1       0.9	containerd (1)
      48.2      11.7          	gnome-terminal-server (1)
      54.8      12.0       0.5	gnome-calendar (1)
      60.9       2.4          	/bin/zsh (12)
      62.8       1.5          	tracker-miner-fs-3 (1)
      66.6      15.1          	WebKitWebProcess (1)
      88.2      15.8          	keepassxc (1)e
      90.1       0.2       1.4	dockerd (1)
     130.5      28.6          	evolution (1)
     218.7       6.3          	python3.9 (3)
     403.2      59.9       6.1	gnome-shell (1)
     462.1      13.4       4.7	wdavdaemon (3)
     494.2     100.3       2.2	[redacted] (5)
     792.9       3.5       0.4	gnome-software (1)
     817.6       3.0       3.4	packagekitd (1)e
     969.0     419.4       2.2	clickhouse (1)
    1245.7       0.2          	[redacted] (1)
    1445.6       0.4          	[redacted] (1)
    3468.0     276.1          	firefox (11)
#  11735.7                32.1	TOTAL USED BY PROCESSES
```
To me, this indicates an incompatibility with the current dependencies bundled with the newer Golang distributions.  

As a workaround, I have added your `psm` binary to my local toolkit, as-is, but obviously feel let down, unable to experience the joy of building it myself. =)

**Comment by johnsonjh** [comment]
Closing / no activity.
